---
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:20880/eureka/"
server:
  port: 8082
spring:
  application:
    name: consumer-pinyougou-shop-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: "jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf8&useSSL=false"
    cloud:
        config:
          discovery:
            enabled: true
            service-id: provider-sellergoods-service
  mvc:
    static-path-pattern: /static/**
    #设置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
mybatis:
  mapper-locations: com.pinyougou.mapper/*.xml
  # 分布式文件系统FDFS配置

fdfs:
  connect-timeout: 600 #连接tracker服务器超时时长
  so-timeout: 1500 #socket链接超时时间
  thumb-image: #缩略图生成参数，可选
    width: 150
    height: 150
  tracker-list: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 192.168.2.120:22122
  resHost: 192.168.2.120
  storagePort: 80